### ISSUE TITLE
undefined method 'queue'  raised in info endpoint.

### ISSUE THREAD

**Issue by DanMegaGamer** [hirefire/hirefire-resource-ruby#66]
Hi.

Since updating from 0.10.1 to 1.0.0 we're intermittently seeing 500s in the hirefire endpoint.

`2024-02-01 11:54:44 +0000 Rack app ("GET /hirefire" - (xxx.xx.xx.xxx)): #<NoMethodError: undefined method 'queue' for {"queue"=>"default", "payload"...`

I haven't been able to work out what the scenario is that triggers the issue, but it's frequent.

It seems queue is being called on a Hash at some points.

ruby 3.3.0
hirefire-resource (1.0.0)
rails (7.1.3)
sidekiq (7.2.1)
sidekiq-ent (7.2.1)
sidekiq-pro (7.2.0)

**Comment by mrrooijen** [comment]
@DanMegaGamer, thanks for reporting the issue. Did you, by any chance, upgrade both hirefire-resource to version 1 and Sidekiq to version 7 (both major) simultaneously?

I think I know what might be happening. I'm currently investigating it, and I will get back to you soon.

**Comment by DanMegaGamer** [comment]
hi @mrrooijen, thanks for reply, we did upgrade hirefire-resource  0.10.1 to 1.0.0 recently, but the update to Sidekq 7.2.0 was back in November. The issue seemed to arise after the hirefire-resource update was deployed.

**Comment by mrrooijen** [comment]
@DanMegaGamer Sidekiq introduced a change in version `7.2.1` where a certain value was changed from a `Hash` to `Sidekiq::Work`. This modification affects how the data of that value should be accessed. I've just released `hirefire-resource v1.0.1`, which should address this issue. Give it a try and let me know how it goes.

**Comment by DanMegaGamer** [comment]
Hey @mrrooijen, that does seem to have fixed the issue, thank you.

**Comment by mrrooijen** [comment]
Great! Thanks for confirming.
